name: Build
on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@main
      - name: Setup JDK 17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Scan Minecraft classes
        run: ./gradlew test -x common:test --continue -Pgenerate=dryRun
        continue-on-error: true
      - name: Generate holders
        run: ./gradlew test -x common:test --continue -Pgenerate=normal
        continue-on-error: true
      - name: Search for mapped methods
        run: ./gradlew test -x common:test
      - name: Analyze test results
        run: ./gradlew common:test
      - name: Build common
        run: ./gradlew common:build -x test
      - name: Build Fabric
        run: ./gradlew -p fabric build -x test
      - name: Build Forge
        run: ./gradlew -p forge build -x test
      - name: Capture build artifacts
        uses: actions/upload-artifact@main
        with:
          name: Mappings
          path: build/release/
      - name: Capture consolidated Minecraft methods
        uses: actions/upload-artifact@main
        with:
          name: Minecraft Methods
          path: build/libraryMethods/
